### ISSUE TITLE
Dockerized wiremock.net does not read static mappings

### ISSUE THREAD

**Issue by muhammadahmadsaeed** [WireMock-Net/WireMock.Net-docker#23]
I am trying to run wiremock .net in docker but it is not reading static files. How to send ReadStaticMappings flag in docker compose?

``` yml
wiremock:
    image: sheyenrath/wiremock.net
    ports:
       - "9091:80"
    volumes:
      - ./wiremock:/home/wiremock
```
