### ISSUE TITLE
Is there a way to allow HTTPS connections

### ISSUE THREAD

**Issue by D-H** [WireMock-Net/WireMock.Net-docker#35]
I ran into an issue where I was not able to mock responses when a client make an HTTPS request rather than an HTTP request. Most Is there a way for Wiremock to support for both HTTP and HTTPS mocking?

This is currently what my docker-compose entry looks like for my Wiremock container. 

```
  users-service-mock:
    container_name: users-service-mock
    image: "sheyenrath/wiremock.net:1.3.3"
    networks:
      - users-https-test
    ports:
      - "80"
    command:
      - "--ReadStaticMappings"
      - "true"
      - "--WireMockLogger"
      - WireMockConsoleLogger
    volumes:
      - type: bind
        source: ./services/http-mocks/users-service-mock
        target: /app/__admin/mappings
```
